// <auto-generated />
using System;
using LogisticsCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogisticsCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200630205314_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogisticsDomain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Node");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            IdentifierName = "CABA",
                            Latitude = -34.613149999999997,
                            Longitude = -58.377229999999997,
                            Name = "CABA"
                        },
                        new
                        {
                            Id = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            IdentifierName = "CORDOBA",
                            Latitude = -31.416668000000001,
                            Longitude = -64.183334000000002,
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            IdentifierName = "CORRIENTES",
                            Latitude = -27.471226000000001,
                            Longitude = -58.839584000000002,
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            IdentifierName = "FORMOSA",
                            Latitude = -26.177530000000001,
                            Longitude = -58.178139999999999,
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            IdentifierName = "LA_PLATA",
                            Latitude = -34.920344999999998,
                            Longitude = -57.969558999999997,
                            Name = "La Plata"
                        },
                        new
                        {
                            Id = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            IdentifierName = "LA_RIOJA",
                            Latitude = -29.411049999999999,
                            Longitude = -66.850669999999994,
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            IdentifierName = "MENDOZA",
                            Latitude = -32.888354999999997,
                            Longitude = -68.838843999999995,
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            IdentifierName = "NEUQUEN",
                            Latitude = -38.951610000000002,
                            Longitude = -68.059100000000001,
                            Name = "Neuquén"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SegmentIdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId", "DestinationId")
                        .IsUnique();

                    b.ToTable("Path");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33d63672-1b3c-4759-b899-061fdcd0b0ff"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-CORDOBA",
                            Weight = 646
                        },
                        new
                        {
                            Id = new Guid("f26ad063-acf8-43d2-8456-c31c148a6ac5"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-CORRIENTES",
                            Weight = 792
                        },
                        new
                        {
                            Id = new Guid("fb9f3d3b-7536-4b47-8fd0-4bb4e0980a16"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-FORMOSA",
                            Weight = 933
                        },
                        new
                        {
                            Id = new Guid("572f803a-78fd-4df5-94ef-acd475c1d033"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-LA_PLATA",
                            Weight = 53
                        },
                        new
                        {
                            Id = new Guid("fef4a3e8-e7fc-43bc-8284-2f58adc466d2"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-LA_RIOJA",
                            Weight = 986
                        },
                        new
                        {
                            Id = new Guid("a86aa52d-a8dd-4c7f-98ad-589c5ccb777f"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-MENDOZA",
                            Weight = 985
                        },
                        new
                        {
                            Id = new Guid("029f2f90-d57d-4065-ba01-e09664223499"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            SegmentIdentifierName = "CABA-NEUQUEN",
                            Weight = 989
                        },
                        new
                        {
                            Id = new Guid("8ceeb850-7344-4e93-a7ae-7c456861b8be"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-CABA",
                            Weight = 646
                        },
                        new
                        {
                            Id = new Guid("909befe3-5901-4598-97b7-61012f52979f"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-CORRIENTES",
                            Weight = 677
                        },
                        new
                        {
                            Id = new Guid("464170a4-c83b-483b-96fa-9a5e360a8354"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-FORMOSA",
                            Weight = 824
                        },
                        new
                        {
                            Id = new Guid("37c7fda5-2989-4a01-b145-bf0b7882b0b8"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-LA_PLATA",
                            Weight = 698
                        },
                        new
                        {
                            Id = new Guid("7cde9b53-bde6-4bd4-997e-ae5155ee1960"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-LA_RIOJA",
                            Weight = 340
                        },
                        new
                        {
                            Id = new Guid("cd0763aa-ee5e-4377-9d44-2af784764bff"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-MENDOZA",
                            Weight = 466
                        },
                        new
                        {
                            Id = new Guid("edd8f7c2-7488-4f4f-96b2-0b8d0f755c5c"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            SegmentIdentifierName = "CORDOBA-NEUQUEN",
                            Weight = 907
                        },
                        new
                        {
                            Id = new Guid("a089451c-5fc7-4210-8559-0abc08090b63"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-CABA",
                            Weight = 792
                        },
                        new
                        {
                            Id = new Guid("4c143705-fc10-4083-a6e1-f7b67b1d616b"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-CORDOBA",
                            Weight = 677
                        },
                        new
                        {
                            Id = new Guid("5fed9efe-1019-4cc4-8aea-9f1798920eea"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-FORMOSA",
                            Weight = 157
                        },
                        new
                        {
                            Id = new Guid("2c2ef3ed-4c2f-49c5-a129-55fa6c5f65f3"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-LA_PLATA",
                            Weight = 830
                        },
                        new
                        {
                            Id = new Guid("de930c55-de32-4cf0-b6f8-f9a88bd87b77"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-LA_RIOJA",
                            Weight = 814
                        },
                        new
                        {
                            Id = new Guid("380e5fbc-f34b-46b6-85b0-0984302438e9"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-MENDOZA",
                            Weight = 1131
                        },
                        new
                        {
                            Id = new Guid("3b112c7e-1b4e-4026-b30b-573bd2c575ba"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            SegmentIdentifierName = "CORRIENTES-NEUQUEN",
                            Weight = 1534
                        },
                        new
                        {
                            Id = new Guid("3ab500ba-95aa-4553-ac52-ec10b2a984c4"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-CABA",
                            Weight = 933
                        },
                        new
                        {
                            Id = new Guid("25d1ceae-aae3-4691-b56b-e3786094a137"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-CORDOBA",
                            Weight = 824
                        },
                        new
                        {
                            Id = new Guid("3df33ba3-3396-4b23-adc3-a4d9c6eaffe2"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-CORRIENTES",
                            Weight = 157
                        },
                        new
                        {
                            Id = new Guid("b7d96228-8df4-40ff-b535-833b8bf16d3c"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-LA_PLATA",
                            Weight = 968
                        },
                        new
                        {
                            Id = new Guid("72613eae-1ad5-46a1-aaea-433a982b1c36"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-LA_RIOJA",
                            Weight = 927
                        },
                        new
                        {
                            Id = new Guid("62da53ee-6546-4636-9f7d-58320ca70792"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-MENDOZA",
                            Weight = 1269
                        },
                        new
                        {
                            Id = new Guid("16ef4ea0-a69c-4c06-adcf-41d3d847aaee"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            SegmentIdentifierName = "FORMOSA-NEUQUEN",
                            Weight = 1690
                        },
                        new
                        {
                            Id = new Guid("0415f6d9-a438-421a-ae74-334681442180"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-CABA",
                            Weight = 53
                        },
                        new
                        {
                            Id = new Guid("8c263b86-ac04-406e-8899-9ba0ae533e4b"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-CORDOBA",
                            Weight = 698
                        },
                        new
                        {
                            Id = new Guid("ea9e0541-9716-43e7-b4e8-282be7f49332"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-CORRIENTES",
                            Weight = 830
                        },
                        new
                        {
                            Id = new Guid("8a639432-687f-4769-a803-7866acd3daac"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-FORMOSA",
                            Weight = 968
                        },
                        new
                        {
                            Id = new Guid("4a316b55-2ae4-4ca8-80c6-9a64bda9a4b8"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-LA_RIOJA",
                            Weight = 1038
                        },
                        new
                        {
                            Id = new Guid("ea10c090-5ee0-40db-9fbf-deb73ba0065f"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-MENDOZA",
                            Weight = 1029
                        },
                        new
                        {
                            Id = new Guid("6cd40ca0-c99f-4ec5-82fb-59ca4b401d34"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            SegmentIdentifierName = "LA_PLATA-NEUQUEN",
                            Weight = 1005
                        },
                        new
                        {
                            Id = new Guid("899aa944-e5e6-4282-9902-11cc12a5924b"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-CABA",
                            Weight = 986
                        },
                        new
                        {
                            Id = new Guid("d1f70af7-79eb-4711-8e7e-a617ef016dff"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-CORDOBA",
                            Weight = 340
                        },
                        new
                        {
                            Id = new Guid("0539ea1e-02f4-437d-b8a1-8667515eb80f"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-CORRIENTES",
                            Weight = 814
                        },
                        new
                        {
                            Id = new Guid("ebedc388-6d17-4303-9432-580c991a0f19"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-FORMOSA",
                            Weight = 927
                        },
                        new
                        {
                            Id = new Guid("e9b96bdd-7088-4cf7-87ef-87c46659efe2"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-LA_PLATA",
                            Weight = 1038
                        },
                        new
                        {
                            Id = new Guid("a014b9a5-7bda-4710-a1b4-9ce738ddcd5c"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-MENDOZA",
                            Weight = 427
                        },
                        new
                        {
                            Id = new Guid("3309c504-d0e5-4aad-8ee1-6c880c9be823"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            SegmentIdentifierName = "LA_RIOJA-NEUQUEN",
                            Weight = 1063
                        },
                        new
                        {
                            Id = new Guid("e712f373-88f3-47b9-9ae6-ad0fa2b37bed"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-CABA",
                            Weight = 985
                        },
                        new
                        {
                            Id = new Guid("27ac43b0-d0f9-4469-a143-f82de63faf63"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-CORDOBA",
                            Weight = 466
                        },
                        new
                        {
                            Id = new Guid("fcf6219a-5d0b-4bf5-bfc5-2b30b83d21f9"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-CORRIENTES",
                            Weight = 1131
                        },
                        new
                        {
                            Id = new Guid("8b1ee88b-e42e-4002-b6e7-7238c1a068df"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-FORMOSA",
                            Weight = 1269
                        },
                        new
                        {
                            Id = new Guid("d5a734b8-8cb8-4889-a6f5-bfb3dbf73f7c"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-LA_PLATA",
                            Weight = 1029
                        },
                        new
                        {
                            Id = new Guid("fced7571-c684-43f7-bee6-10a63788e9f3"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-LA_RIOJA",
                            Weight = 427
                        },
                        new
                        {
                            Id = new Guid("1311e88a-62b1-423f-9dba-b9c35f393585"),
                            DestinationId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            OriginId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            SegmentIdentifierName = "MENDOZA-NEUQUEN",
                            Weight = 676
                        },
                        new
                        {
                            Id = new Guid("589ed2b0-990c-472c-a0fa-f5a97de79c04"),
                            DestinationId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-CABA",
                            Weight = 989
                        },
                        new
                        {
                            Id = new Guid("1c49cb4f-edd6-4915-a2fb-033e2132ed9d"),
                            DestinationId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-CORDOBA",
                            Weight = 907
                        },
                        new
                        {
                            Id = new Guid("5246612a-5bb0-4fca-81be-0607fcc4bf4c"),
                            DestinationId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-CORRIENTES",
                            Weight = 1534
                        },
                        new
                        {
                            Id = new Guid("fd73aca9-ae3e-4ad0-b193-a43ec23feaa0"),
                            DestinationId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-FORMOSA",
                            Weight = 1690
                        },
                        new
                        {
                            Id = new Guid("de36b12f-6ffc-4e98-bd68-aff85c5d69fe"),
                            DestinationId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-LA_PLATA",
                            Weight = 1005
                        },
                        new
                        {
                            Id = new Guid("1c4d640a-f3d4-4816-8001-9647b69e55b4"),
                            DestinationId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-LA_RIOJA",
                            Weight = 1063
                        },
                        new
                        {
                            Id = new Guid("cfb26a48-356f-46a9-8d16-a57ba6b66c1b"),
                            DestinationId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            OriginId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            SegmentIdentifierName = "NEUQUEN-MENDOZA",
                            Weight = 676
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Route");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Detail = "LA_RIOJA - CORDOBA - NEUQUEN - CABA - FORMOSA - LA_RIOJA",
                            Distance = 4096
                        },
                        new
                        {
                            Id = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Detail = "CORRIENTES - LA_PLATA - NEUQUEN - MENDOZA - LA_RIOJA - CORRIENTES",
                            Distance = 3752
                        },
                        new
                        {
                            Id = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            Detail = "FORMOSA - CORRIENTES - CABA - LA_PLATA - FORMOSA",
                            Distance = 1970
                        },
                        new
                        {
                            Id = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Detail = "NEUQUEN - MENDOZA - LA_RIOJA - FORMOSA - CORDOBA - NEUQUEN",
                            Distance = 3761
                        },
                        new
                        {
                            Id = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            Detail = "LA_RIOJA - CORRIENTES - CABA - LA_PLATA - NEUQUEN - CORDOBA - LA_RIOJA",
                            Distance = 3911
                        },
                        new
                        {
                            Id = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Detail = "MENDOZA - LA_PLATA - FORMOSA - CORDOBA - MENDOZA",
                            Distance = 3287
                        },
                        new
                        {
                            Id = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Detail = "CORRIENTES - LA_PLATA - CABA - MENDOZA - CORDOBA - CORRIENTES",
                            Distance = 3011
                        },
                        new
                        {
                            Id = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            Detail = "CORRIENTES - MENDOZA - CABA - LA_PLATA - CORRIENTES",
                            Distance = 2999
                        });
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "NodeId", "Order");

                    b.HasIndex("NodeId");

                    b.ToTable("RouteNode");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            NodeId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            NodeId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            NodeId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            NodeId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("e6689645-b9b7-4157-bb31-f01834331e13"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            NodeId = new Guid("6397a4d0-ac78-47e8-84e1-8d8294bd2b8f"),
                            Order = 7
                        },
                        new
                        {
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            NodeId = new Guid("30e1b05b-14bc-40ad-83fa-6298f31e12ce"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            NodeId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("a4a245bf-03c0-4f40-aff5-7dcb1a3b1a5c"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            NodeId = new Guid("c8245920-9382-494e-a20f-aaef16ad15e2"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            NodeId = new Guid("e090d74f-3f99-42b1-b248-68c6b7ab5c96"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            NodeId = new Guid("c2e5b0ad-e569-42f2-a1d7-23339305c8f0"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            NodeId = new Guid("80899bc6-4906-4165-bc3c-d183e0a2da28"),
                            Order = 5
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateScheduled")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransportationVehicleLicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSegmentId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TransportationVehicleLicensePlate");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41bdefb2-714d-4f9d-8fa0-c460fad12aaf"),
                            DateScheduled = new DateTime(2020, 7, 12, 17, 53, 13, 763, DateTimeKind.Local).AddTicks(9280),
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("38769566-f5eb-4e20-b593-fd9582bdd555"),
                            DateCompleted = new DateTime(2020, 6, 29, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(2920),
                            DateScheduled = new DateTime(2020, 6, 26, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(2920),
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("567134f7-9cb9-4c1d-ac04-5a77b583bd6b"),
                            DateCompleted = new DateTime(2020, 6, 25, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4430),
                            DateScheduled = new DateTime(2020, 6, 22, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4430),
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("d13456ec-530f-4e68-87d9-1e30c2587429"),
                            DateCompleted = new DateTime(2020, 6, 21, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4460),
                            DateScheduled = new DateTime(2020, 6, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4460),
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("f24b939b-a81e-4f66-bc1c-21e380aa5f44"),
                            DateCompleted = new DateTime(2020, 6, 17, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4470),
                            DateScheduled = new DateTime(2020, 6, 14, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4470),
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("e6dd576d-d442-4d53-88a7-f0aa9d57f254"),
                            DateCompleted = new DateTime(2020, 6, 13, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4480),
                            DateScheduled = new DateTime(2020, 6, 10, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4480),
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("dd458b44-3db2-49c3-b7e4-94f6afe3b6f8"),
                            DateCompleted = new DateTime(2020, 6, 9, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4490),
                            DateScheduled = new DateTime(2020, 6, 6, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4490),
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("1251e3fb-c2a7-4870-b113-fee4581588eb"),
                            DateCompleted = new DateTime(2020, 6, 5, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4490),
                            DateScheduled = new DateTime(2020, 6, 2, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4490),
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("baccddf7-dee4-4cee-842f-09c26f9150dd"),
                            DateCompleted = new DateTime(2020, 6, 1, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4500),
                            DateScheduled = new DateTime(2020, 5, 29, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4500),
                            RouteId = new Guid("a7d2740c-8ecc-4498-b5c4-d9671c894640"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("2a113c2c-4431-4b26-b978-22c248ac1b59"),
                            CurrentSegmentId = new Guid("6cd40ca0-c99f-4ec5-82fb-59ca4b401d34"),
                            DateScheduled = new DateTime(2020, 7, 1, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(4500),
                            RouteId = new Guid("730d543a-584e-4fc8-a802-174a69b88aa0"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "ALPHA_1"
                        },
                        new
                        {
                            Id = new Guid("35208d6e-9a61-45d8-95a1-31352d1c5e44"),
                            DateScheduled = new DateTime(2020, 7, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6790),
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("e9abceb9-0abb-4c89-b0bd-e596ecb218c6"),
                            DateCompleted = new DateTime(2020, 5, 20, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6810),
                            DateScheduled = new DateTime(2020, 5, 17, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6810),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("2f2b3f57-42dd-4d1e-aa65-c6b9c46a81ab"),
                            DateCompleted = new DateTime(2020, 5, 16, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6810),
                            DateScheduled = new DateTime(2020, 5, 13, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6810),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("20869236-d88c-4341-9818-a61209e4a966"),
                            DateCompleted = new DateTime(2020, 5, 12, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6820),
                            DateScheduled = new DateTime(2020, 5, 9, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6820),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("b34f00ee-6198-4287-acd1-91e6e69682b9"),
                            DateCompleted = new DateTime(2020, 5, 8, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6820),
                            DateScheduled = new DateTime(2020, 5, 5, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6820),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("28238c60-f1a2-4803-b6b5-93360d1692e0"),
                            DateCompleted = new DateTime(2020, 5, 4, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6830),
                            DateScheduled = new DateTime(2020, 5, 1, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6830),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("902414e7-62ee-416f-af3f-ace5163399b2"),
                            DateCompleted = new DateTime(2020, 4, 30, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6830),
                            DateScheduled = new DateTime(2020, 4, 27, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6830),
                            RouteId = new Guid("78a6ed32-a30b-4cfe-84d6-f1e67bce6bde"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("9ce39451-5685-4bbc-94ee-a77717fe65f7"),
                            DateCompleted = new DateTime(2020, 4, 26, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6860),
                            DateScheduled = new DateTime(2020, 4, 23, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6860),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("fec66c38-0819-4862-9f23-029407d2527e"),
                            CurrentSegmentId = new Guid("ebedc388-6d17-4303-9432-580c991a0f19"),
                            DateScheduled = new DateTime(2020, 7, 2, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6860),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("837e7ff9-c056-4654-9007-b33c46ffeb01"),
                            DateCompleted = new DateTime(2020, 4, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6900),
                            DateScheduled = new DateTime(2020, 4, 15, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6900),
                            RouteId = new Guid("1eb8608f-40aa-4539-90c6-5a01bb51ca3c"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "BETA_2"
                        },
                        new
                        {
                            Id = new Guid("e75317a2-f5bc-415b-a201-f158002854af"),
                            DateScheduled = new DateTime(2020, 7, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6910),
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("1e3ef17b-203d-481a-8dd2-3dab9711546d"),
                            DateCompleted = new DateTime(2020, 4, 10, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6910),
                            DateScheduled = new DateTime(2020, 4, 7, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6910),
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("d45720fd-c44b-4ae7-b164-12cc023fe592"),
                            DateCompleted = new DateTime(2020, 4, 6, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6920),
                            DateScheduled = new DateTime(2020, 4, 3, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6920),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("90b4b04f-9417-44f9-bee7-9fdf2440f6b1"),
                            DateCompleted = new DateTime(2020, 4, 2, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6920),
                            DateScheduled = new DateTime(2020, 3, 30, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(6920),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("7233b3f5-1ae1-456b-a24a-46d9f9c55866"),
                            DateCompleted = new DateTime(2020, 3, 29, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7160),
                            DateScheduled = new DateTime(2020, 3, 26, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7160),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("280a69b8-d5e0-48e5-8645-088804adb81a"),
                            DateCompleted = new DateTime(2020, 3, 25, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7170),
                            DateScheduled = new DateTime(2020, 3, 22, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7170),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("6f236aab-16c0-4950-9bb9-99efb2fa4cc9"),
                            DateCompleted = new DateTime(2020, 3, 21, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7170),
                            DateScheduled = new DateTime(2020, 3, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7170),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("067d730a-4005-4850-b851-b83871d69d7c"),
                            CurrentSegmentId = new Guid("25d1ceae-aae3-4691-b56b-e3786094a137"),
                            DateScheduled = new DateTime(2020, 7, 3, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7180),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("8e583e2d-0841-4901-be03-d1ff1ac6ee35"),
                            DateCompleted = new DateTime(2020, 3, 13, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7190),
                            DateScheduled = new DateTime(2020, 3, 10, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7190),
                            RouteId = new Guid("2f4b3283-5633-49ec-bf68-cc21719eebdd"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("f0f269e5-1e21-4bc0-917d-37110dfa749a"),
                            DateCompleted = new DateTime(2020, 3, 9, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7190),
                            DateScheduled = new DateTime(2020, 3, 6, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7190),
                            RouteId = new Guid("77e03db2-a2ed-46c4-bcd7-15f6bfec8faf"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "GAMMA_3"
                        },
                        new
                        {
                            Id = new Guid("faac2394-2fb3-4e31-8940-18372a200fca"),
                            DateCompleted = new DateTime(2020, 3, 5, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7200),
                            DateScheduled = new DateTime(2020, 3, 2, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7200),
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("0808a5f2-613e-4963-bf20-2ffe6de72e7d"),
                            DateCompleted = new DateTime(2020, 3, 1, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7210),
                            DateScheduled = new DateTime(2020, 2, 27, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7210),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("32776d56-ed5d-4b5a-a6da-1dba5f2a0c9c"),
                            DateCompleted = new DateTime(2020, 2, 26, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7210),
                            DateScheduled = new DateTime(2020, 2, 23, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7210),
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("4a56eff9-a924-472f-95c6-aebb3b47d2f6"),
                            DateCompleted = new DateTime(2020, 2, 22, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7220),
                            DateScheduled = new DateTime(2020, 2, 19, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7220),
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("3cae1dd2-81c7-4134-b6b1-52633d7a7533"),
                            DateCompleted = new DateTime(2020, 2, 18, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7220),
                            DateScheduled = new DateTime(2020, 2, 15, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7220),
                            RouteId = new Guid("7205cf14-eaba-44fa-a83b-c547e4427589"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("2a44d112-f096-4ae8-ae7f-0d9e7bdd4484"),
                            DateCompleted = new DateTime(2020, 2, 14, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            DateScheduled = new DateTime(2020, 2, 11, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("78abebf9-9841-4037-ad67-964fd6bca374"),
                            DateCompleted = new DateTime(2020, 2, 10, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            DateScheduled = new DateTime(2020, 2, 7, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("e90ca4d9-7752-4f2b-a914-c2aac28016e1"),
                            DateCompleted = new DateTime(2020, 2, 6, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            DateScheduled = new DateTime(2020, 2, 3, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7230),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("78b224cd-620f-4cac-9493-4b60a8c740ca"),
                            DateCompleted = new DateTime(2020, 2, 2, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7240),
                            DateScheduled = new DateTime(2020, 1, 30, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7240),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        },
                        new
                        {
                            Id = new Guid("bdc62c9a-fd8d-4a6f-97e7-9f7bc5f287a9"),
                            DateCompleted = new DateTime(2020, 1, 29, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7240),
                            DateScheduled = new DateTime(2020, 1, 26, 17, 53, 13, 777, DateTimeKind.Local).AddTicks(7240),
                            RouteId = new Guid("16be5ffb-352f-466b-b0ab-9e7f1a748b1a"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "EPSILON_4"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.TransportationVehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LicensePlate");

                    b.ToTable("TransportationVehicle");

                    b.HasData(
                        new
                        {
                            LicensePlate = "ALPHA_1",
                            Model = "Scania G 410",
                            Year = 2000
                        },
                        new
                        {
                            LicensePlate = "BETA_2",
                            Model = "Scania P 320",
                            Year = 2010
                        },
                        new
                        {
                            LicensePlate = "GAMMA_3",
                            Model = "Scania R 450",
                            Year = 2015
                        },
                        new
                        {
                            LicensePlate = "EPSILON_4",
                            Model = "Scania R 620",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Destination")
                        .WithMany("PathAsDestination")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Node", "Origin")
                        .WithMany("PathAsOrigin")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("RouteNodes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.HasOne("LogisticsDomain.Path", "CurrentSegment")
                        .WithMany()
                        .HasForeignKey("CurrentSegmentId");

                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("Shippings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.TransportationVehicle", "TransportationVehicle")
                        .WithMany("Shippings")
                        .HasForeignKey("TransportationVehicleLicensePlate")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
