// <auto-generated />
using System;
using LogisticsCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogisticsCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200629203555_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogisticsDomain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Node");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            IdentifierName = "CABA",
                            Latitude = -34.613149999999997,
                            Longitude = -58.377229999999997,
                            Name = "CABA"
                        },
                        new
                        {
                            Id = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            IdentifierName = "CORDOBA",
                            Latitude = -31.416668000000001,
                            Longitude = -64.183334000000002,
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            IdentifierName = "CORRIENTES",
                            Latitude = -27.471226000000001,
                            Longitude = -58.839584000000002,
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            IdentifierName = "FORMOSA",
                            Latitude = -26.177530000000001,
                            Longitude = -58.178139999999999,
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            IdentifierName = "LA_PLATA",
                            Latitude = -34.920344999999998,
                            Longitude = -57.969558999999997,
                            Name = "La Plata"
                        },
                        new
                        {
                            Id = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            IdentifierName = "LA_RIOJA",
                            Latitude = -29.411049999999999,
                            Longitude = -66.850669999999994,
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            IdentifierName = "MENDOZA",
                            Latitude = -32.888354999999997,
                            Longitude = -68.838843999999995,
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            IdentifierName = "NEUQUEN",
                            Latitude = -38.951610000000002,
                            Longitude = -68.059100000000001,
                            Name = "Neuquén"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.Property<Guid>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SegmentIdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("OriginId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Path");

                    b.HasData(
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "CABA-CORDOBA",
                            Weight = 646
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "CABA-CORRIENTES",
                            Weight = 792
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "CABA-FORMOSA",
                            Weight = 933
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "CABA-LA_PLATA",
                            Weight = 53
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "CABA-LA_RIOJA",
                            Weight = 986
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "CABA-MENDOZA",
                            Weight = 985
                        },
                        new
                        {
                            OriginId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "CABA-NEUQUEN",
                            Weight = 989
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "CORDOBA-CABA",
                            Weight = 646
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "CORDOBA-CORRIENTES",
                            Weight = 677
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "CORDOBA-FORMOSA",
                            Weight = 824
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "CORDOBA-LA_PLATA",
                            Weight = 698
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "CORDOBA-LA_RIOJA",
                            Weight = 340
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "CORDOBA-MENDOZA",
                            Weight = 466
                        },
                        new
                        {
                            OriginId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "CORDOBA-NEUQUEN",
                            Weight = 907
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "CORRIENTES-CABA",
                            Weight = 792
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "CORRIENTES-CORDOBA",
                            Weight = 677
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "CORRIENTES-FORMOSA",
                            Weight = 157
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "CORRIENTES-LA_PLATA",
                            Weight = 830
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "CORRIENTES-LA_RIOJA",
                            Weight = 814
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "CORRIENTES-MENDOZA",
                            Weight = 1131
                        },
                        new
                        {
                            OriginId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "CORRIENTES-NEUQUEN",
                            Weight = 1534
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "FORMOSA-CABA",
                            Weight = 933
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "FORMOSA-CORDOBA",
                            Weight = 824
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "FORMOSA-CORRIENTES",
                            Weight = 157
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "FORMOSA-LA_PLATA",
                            Weight = 968
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "FORMOSA-LA_RIOJA",
                            Weight = 927
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "FORMOSA-MENDOZA",
                            Weight = 1269
                        },
                        new
                        {
                            OriginId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "FORMOSA-NEUQUEN",
                            Weight = 1690
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "LA_PLATA-CABA",
                            Weight = 53
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "LA_PLATA-CORDOBA",
                            Weight = 698
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "LA_PLATA-CORRIENTES",
                            Weight = 830
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "LA_PLATA-FORMOSA",
                            Weight = 968
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "LA_PLATA-LA_RIOJA",
                            Weight = 1038
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "LA_PLATA-MENDOZA",
                            Weight = 1029
                        },
                        new
                        {
                            OriginId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "LA_PLATA-NEUQUEN",
                            Weight = 1005
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "LA_RIOJA-CABA",
                            Weight = 986
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "LA_RIOJA-CORDOBA",
                            Weight = 340
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "LA_RIOJA-CORRIENTES",
                            Weight = 814
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "LA_RIOJA-FORMOSA",
                            Weight = 927
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "LA_RIOJA-LA_PLATA",
                            Weight = 1038
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "LA_RIOJA-MENDOZA",
                            Weight = 427
                        },
                        new
                        {
                            OriginId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "LA_RIOJA-NEUQUEN",
                            Weight = 1063
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "MENDOZA-CABA",
                            Weight = 985
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "MENDOZA-CORDOBA",
                            Weight = 466
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "MENDOZA-CORRIENTES",
                            Weight = 1131
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "MENDOZA-FORMOSA",
                            Weight = 1269
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "MENDOZA-LA_PLATA",
                            Weight = 1029
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "MENDOZA-LA_RIOJA",
                            Weight = 427
                        },
                        new
                        {
                            OriginId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            DestinationId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            SegmentIdentifierName = "MENDOZA-NEUQUEN",
                            Weight = 676
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            SegmentIdentifierName = "NEUQUEN-CABA",
                            Weight = 989
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            SegmentIdentifierName = "NEUQUEN-CORDOBA",
                            Weight = 907
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            SegmentIdentifierName = "NEUQUEN-CORRIENTES",
                            Weight = 1534
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            SegmentIdentifierName = "NEUQUEN-FORMOSA",
                            Weight = 1690
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            SegmentIdentifierName = "NEUQUEN-LA_PLATA",
                            Weight = 1005
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            SegmentIdentifierName = "NEUQUEN-LA_RIOJA",
                            Weight = 1063
                        },
                        new
                        {
                            OriginId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            DestinationId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            SegmentIdentifierName = "NEUQUEN-MENDOZA",
                            Weight = 676
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Route");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Detail = "LA_RIOJA - CORDOBA - NEUQUEN - CABA - FORMOSA - LA_RIOJA",
                            Distance = 4096
                        },
                        new
                        {
                            Id = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Detail = "CORRIENTES - LA_PLATA - NEUQUEN - MENDOZA - LA_RIOJA - CORRIENTES",
                            Distance = 3752
                        },
                        new
                        {
                            Id = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            Detail = "FORMOSA - CORRIENTES - CABA - LA_PLATA - FORMOSA",
                            Distance = 1970
                        },
                        new
                        {
                            Id = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Detail = "NEUQUEN - MENDOZA - LA_RIOJA - FORMOSA - CORDOBA - NEUQUEN",
                            Distance = 3761
                        },
                        new
                        {
                            Id = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Detail = "LA_RIOJA - CORRIENTES - CABA - LA_PLATA - NEUQUEN - CORDOBA - LA_RIOJA",
                            Distance = 3911
                        },
                        new
                        {
                            Id = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            Detail = "MENDOZA - LA_PLATA - FORMOSA - CORDOBA - MENDOZA",
                            Distance = 3287
                        },
                        new
                        {
                            Id = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Detail = "CORRIENTES - LA_PLATA - CABA - MENDOZA - CORDOBA - CORRIENTES",
                            Distance = 3011
                        });
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "NodeId", "Order");

                    b.HasIndex("NodeId");

                    b.ToTable("RouteNode");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            NodeId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            NodeId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            NodeId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            NodeId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            NodeId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("de1449c8-ab97-4fb3-925d-8ad816283ada"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            NodeId = new Guid("a323c1a9-01ff-49a0-bb2e-8993039648c2"),
                            Order = 7
                        },
                        new
                        {
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            NodeId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            NodeId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            NodeId = new Guid("c9464a1e-be38-438f-a6e7-ae8d1144d21b"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            NodeId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            NodeId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("c25cbacb-0811-4ca9-b397-953e44c45d12"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("70bf3253-1e35-4045-86f0-1364f92f7b98"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("2d798aea-dccb-457c-b694-489b25742641"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("03566cd3-a968-4795-966c-f96882b8a72c"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            NodeId = new Guid("de1cb888-20c0-4f54-99ec-f011206566b4"),
                            Order = 6
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentSegment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateScheduled")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransportationVehicleLicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("TransportationVehicleLicensePlate");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e1f2f2e-1ef5-4972-bad1-39e9b48a6d55"),
                            CurrentSegment = "LA_PLATA-CABA",
                            DateScheduled = new DateTime(2020, 6, 27, 17, 35, 54, 649, DateTimeKind.Local).AddTicks(6300),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("40996715-90e0-4ece-b815-76d23dccc2de"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7510),
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("5a87c6ac-7792-4188-aabb-3283c45c0380"),
                            DateScheduled = new DateTime(2020, 7, 14, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7560),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("fcd7a3c2-efdf-4412-94c4-b73de61669d0"),
                            DateScheduled = new DateTime(2020, 7, 6, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7580),
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("62acd632-b241-4af3-88a0-e4f7a3b59ab7"),
                            DateScheduled = new DateTime(2020, 7, 17, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7590),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("0f2d7850-6c98-4963-9ece-724937f122d0"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7610),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("55f762a0-1730-41b0-9263-ab7968c47007"),
                            DateScheduled = new DateTime(2020, 7, 8, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7630),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("368c9b75-6327-4712-a044-4d29be2361aa"),
                            DateScheduled = new DateTime(2020, 7, 15, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7640),
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("5a5df9d5-6cac-4a56-96f3-ffa581c4f2f4"),
                            DateScheduled = new DateTime(2020, 7, 14, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7650),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("1e3d3f18-9e28-4252-b00d-b1b85edc7a98"),
                            DateScheduled = new DateTime(2020, 7, 13, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7670),
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("ca739277-ba56-48da-bd26-dae77fc7971e"),
                            CurrentSegment = "MENDOZA-LA_RIOJA",
                            DateScheduled = new DateTime(2020, 6, 28, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7670),
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("289f1115-b2a8-453f-89b1-1720a52f8419"),
                            DateScheduled = new DateTime(2020, 7, 12, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7710),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("b783861f-3804-4060-8244-5ca5a0e49d4d"),
                            DateScheduled = new DateTime(2020, 7, 8, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7720),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("f1780910-2e43-4d70-a1f4-4aefcade6199"),
                            DateScheduled = new DateTime(2020, 7, 7, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7730),
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("4383b5bc-58f8-4350-8598-008819cad4ed"),
                            DateScheduled = new DateTime(2020, 7, 15, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7750),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("e342589e-4f3e-491d-a705-ccaabeaba814"),
                            DateScheduled = new DateTime(2020, 7, 4, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7760),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("9bd0a779-6663-4c4e-bd9a-cb4774b464e2"),
                            DateScheduled = new DateTime(2020, 7, 9, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7830),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("606f4f28-c703-47f8-a28b-0bc8ca5b8f92"),
                            DateScheduled = new DateTime(2020, 7, 17, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7850),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("9256ac4f-a61a-40d3-839a-3879daa9b125"),
                            DateScheduled = new DateTime(2020, 7, 11, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7870),
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("f9d9bc86-7e98-46a8-8783-db14c1e9a342"),
                            DateScheduled = new DateTime(2020, 7, 7, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7880),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("7c1c638d-da8f-42cc-8147-5f80e625f555"),
                            CurrentSegment = "CORDOBA-LA_RIOJA",
                            DateScheduled = new DateTime(2020, 6, 26, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7880),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("2d8d0805-8217-4546-be28-ee356afe469b"),
                            DateScheduled = new DateTime(2020, 7, 18, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7900),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("8f319325-e6ed-4222-b717-bd6e0df926e1"),
                            DateScheduled = new DateTime(2020, 7, 8, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7910),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("78db4147-7baf-4e2e-8e92-e8855866e21d"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7920),
                            RouteId = new Guid("a09a584f-dcf9-4580-a591-f84cbd624081"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("416cc51f-8202-440d-bb3a-4ee0d8ba8535"),
                            DateScheduled = new DateTime(2020, 7, 14, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7940),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("356b2cf8-ae30-42ad-b941-edf99c117802"),
                            DateScheduled = new DateTime(2020, 7, 9, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7950),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("540006bc-657e-491b-b049-8167bb257a91"),
                            DateScheduled = new DateTime(2020, 7, 11, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7960),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("1d4c1323-3929-4847-9ab2-81854186cbe8"),
                            DateScheduled = new DateTime(2020, 7, 9, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7970),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("3b1bf70f-0edb-4e0d-a799-7be9a49e902b"),
                            DateScheduled = new DateTime(2020, 7, 16, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(7990),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("88ca0797-8c64-474f-8a87-77afc4f5be47"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8000),
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("52fa0979-7abb-4a25-b8dd-a0141555b902"),
                            CurrentSegment = "LA_RIOJA-CORDOBA",
                            DateScheduled = new DateTime(2020, 6, 27, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8000),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("5e805636-e28f-43f1-8174-190efbc36b93"),
                            DateScheduled = new DateTime(2020, 7, 14, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8020),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("2f9fb849-ffb4-40b5-84a4-d92e26d08658"),
                            DateScheduled = new DateTime(2020, 7, 13, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8030),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("5c5b96ba-b5e9-4030-9db3-c4b2efab38f4"),
                            DateScheduled = new DateTime(2020, 7, 15, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8050),
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("addc39d3-988a-4bf9-9c81-837175da1453"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8060),
                            RouteId = new Guid("a858ad55-d21e-4df3-b391-4d596d5f691c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("126c35b7-90a5-44ef-838a-5add0b3eeb99"),
                            DateScheduled = new DateTime(2020, 7, 10, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8070),
                            RouteId = new Guid("02adbc1e-cf29-45f0-8da6-c1d2048d55b9"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("ee897850-31a1-40df-9396-ec933a726cb9"),
                            DateScheduled = new DateTime(2020, 7, 6, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8080),
                            RouteId = new Guid("325281d9-d884-4268-ac95-765d64751d17"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("933fab86-8c59-4b1e-b7a7-953973a8690a"),
                            DateScheduled = new DateTime(2020, 7, 7, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8100),
                            RouteId = new Guid("f05862c8-a668-48e2-bd5c-7b5299e8f441"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("9da3e363-a762-4064-8c78-b0222dacd709"),
                            DateScheduled = new DateTime(2020, 7, 14, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8110),
                            RouteId = new Guid("aec7ff0e-1c13-4215-874c-5e8faa3d227c"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("3a134301-92e1-45a0-893d-e6d846e38988"),
                            DateScheduled = new DateTime(2020, 7, 5, 17, 35, 54, 661, DateTimeKind.Local).AddTicks(8120),
                            RouteId = new Guid("668379c4-1cba-4be0-bfeb-3644e4fc8d92"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.TransportationVehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LicensePlate");

                    b.ToTable("TransportationVehicle");

                    b.HasData(
                        new
                        {
                            LicensePlate = "SCANIA_1",
                            Model = "Scania G 410",
                            Year = 2000
                        },
                        new
                        {
                            LicensePlate = "SCANIA_2",
                            Model = "Scania P 320",
                            Year = 2010
                        },
                        new
                        {
                            LicensePlate = "SCANIA_3",
                            Model = "Scania R 450",
                            Year = 2015
                        },
                        new
                        {
                            LicensePlate = "SCANIA_4",
                            Model = "Scania R 620",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Destination")
                        .WithMany("PathAsDestination")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Node", "Origin")
                        .WithMany("PathAsOrigin")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("RouteNodes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("Shippings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.TransportationVehicle", "TransportationVehicle")
                        .WithMany("Shippings")
                        .HasForeignKey("TransportationVehicleLicensePlate")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
