// <auto-generated />
using System;
using LogisticsCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LogisticsCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200630184802_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogisticsDomain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Node");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            IdentifierName = "CABA",
                            Latitude = -34.613149999999997,
                            Longitude = -58.377229999999997,
                            Name = "CABA"
                        },
                        new
                        {
                            Id = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            IdentifierName = "CORDOBA",
                            Latitude = -31.416668000000001,
                            Longitude = -64.183334000000002,
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            IdentifierName = "CORRIENTES",
                            Latitude = -27.471226000000001,
                            Longitude = -58.839584000000002,
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            IdentifierName = "FORMOSA",
                            Latitude = -26.177530000000001,
                            Longitude = -58.178139999999999,
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            IdentifierName = "LA_PLATA",
                            Latitude = -34.920344999999998,
                            Longitude = -57.969558999999997,
                            Name = "La Plata"
                        },
                        new
                        {
                            Id = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            IdentifierName = "LA_RIOJA",
                            Latitude = -29.411049999999999,
                            Longitude = -66.850669999999994,
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            IdentifierName = "MENDOZA",
                            Latitude = -32.888354999999997,
                            Longitude = -68.838843999999995,
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            IdentifierName = "NEUQUEN",
                            Latitude = -38.951610000000002,
                            Longitude = -68.059100000000001,
                            Name = "Neuquén"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SegmentIdentifierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId", "DestinationId")
                        .IsUnique();

                    b.ToTable("Path");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2df3f33-c41a-4336-9edc-fa89b561392c"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-CORDOBA",
                            Weight = 646
                        },
                        new
                        {
                            Id = new Guid("eb2d94fc-3e68-499f-b0a3-098c7885f494"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-CORRIENTES",
                            Weight = 792
                        },
                        new
                        {
                            Id = new Guid("f27d7dda-b72c-47d7-8161-71841f32a943"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-FORMOSA",
                            Weight = 933
                        },
                        new
                        {
                            Id = new Guid("b3223a2a-dcb9-453d-b7ca-416694d2a997"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-LA_PLATA",
                            Weight = 53
                        },
                        new
                        {
                            Id = new Guid("913d1d9c-af98-4f71-8875-62b2074e639a"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-LA_RIOJA",
                            Weight = 986
                        },
                        new
                        {
                            Id = new Guid("1ab5ae19-edac-408d-aa1a-673dca34e80e"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-MENDOZA",
                            Weight = 985
                        },
                        new
                        {
                            Id = new Guid("45a16731-80f7-4271-9c93-31c22362e2ca"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            SegmentIdentifierName = "CABA-NEUQUEN",
                            Weight = 989
                        },
                        new
                        {
                            Id = new Guid("08fa1839-ab05-403e-91fa-d43b1a079649"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-CABA",
                            Weight = 646
                        },
                        new
                        {
                            Id = new Guid("570afa63-7343-4994-8624-9a7f07310360"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-CORRIENTES",
                            Weight = 677
                        },
                        new
                        {
                            Id = new Guid("6045f1fb-5559-45db-9d21-2757fdb4bbaa"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-FORMOSA",
                            Weight = 824
                        },
                        new
                        {
                            Id = new Guid("7d25ec31-b96b-49a2-9964-2f483d1b945e"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-LA_PLATA",
                            Weight = 698
                        },
                        new
                        {
                            Id = new Guid("0843dab0-91b5-4fe5-aac7-2d090cec0ffd"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-LA_RIOJA",
                            Weight = 340
                        },
                        new
                        {
                            Id = new Guid("b8f21712-af7a-47b9-bd1b-d1161daaccfb"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-MENDOZA",
                            Weight = 466
                        },
                        new
                        {
                            Id = new Guid("2c435ee7-cff0-452f-8c0a-a7c8bf8c4628"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            SegmentIdentifierName = "CORDOBA-NEUQUEN",
                            Weight = 907
                        },
                        new
                        {
                            Id = new Guid("d089e938-733a-44bc-b398-7ec313369fa1"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-CABA",
                            Weight = 792
                        },
                        new
                        {
                            Id = new Guid("1a2b3259-21c4-4a22-9c3b-ee15423b32b1"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-CORDOBA",
                            Weight = 677
                        },
                        new
                        {
                            Id = new Guid("1d728f25-5a5d-4c93-acab-557080194eb8"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-FORMOSA",
                            Weight = 157
                        },
                        new
                        {
                            Id = new Guid("68d21fef-82b1-4000-8af2-f10b1c593222"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-LA_PLATA",
                            Weight = 830
                        },
                        new
                        {
                            Id = new Guid("2ddd7bdd-13cf-4a53-a15b-be5fa219c96f"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-LA_RIOJA",
                            Weight = 814
                        },
                        new
                        {
                            Id = new Guid("bf81606d-5920-4907-a76e-d1a8e7c9079e"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-MENDOZA",
                            Weight = 1131
                        },
                        new
                        {
                            Id = new Guid("2951ab87-8ffc-4023-9c3a-4916b9282da4"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            SegmentIdentifierName = "CORRIENTES-NEUQUEN",
                            Weight = 1534
                        },
                        new
                        {
                            Id = new Guid("8c47ebd4-fdc7-45ba-ad23-77a88111d46c"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-CABA",
                            Weight = 933
                        },
                        new
                        {
                            Id = new Guid("c9e01e9b-9f69-4507-9faa-4cc805bff3f6"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-CORDOBA",
                            Weight = 824
                        },
                        new
                        {
                            Id = new Guid("5041185a-64b9-4f9a-9983-f7ca6c42968e"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-CORRIENTES",
                            Weight = 157
                        },
                        new
                        {
                            Id = new Guid("206df8c8-7482-4363-9257-05732bacae0f"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-LA_PLATA",
                            Weight = 968
                        },
                        new
                        {
                            Id = new Guid("68c22067-8a9f-430d-bdba-04960ce95b7d"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-LA_RIOJA",
                            Weight = 927
                        },
                        new
                        {
                            Id = new Guid("18887803-e0e4-4832-9d12-daad31d83b92"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-MENDOZA",
                            Weight = 1269
                        },
                        new
                        {
                            Id = new Guid("cb367466-1836-4015-88e5-e9e709b83b5b"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            SegmentIdentifierName = "FORMOSA-NEUQUEN",
                            Weight = 1690
                        },
                        new
                        {
                            Id = new Guid("a64a46fb-d9cf-40b4-87b9-23d795b174df"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-CABA",
                            Weight = 53
                        },
                        new
                        {
                            Id = new Guid("279234ff-3f9f-4f43-b4ff-37db92ef46a7"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-CORDOBA",
                            Weight = 698
                        },
                        new
                        {
                            Id = new Guid("ecebf3e9-c095-4721-9c69-63b4fe1340f9"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-CORRIENTES",
                            Weight = 830
                        },
                        new
                        {
                            Id = new Guid("bdace210-3d55-4b1e-8046-c0cefe46194c"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-FORMOSA",
                            Weight = 968
                        },
                        new
                        {
                            Id = new Guid("7ea7d835-2479-4f8f-9d88-089b09998289"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-LA_RIOJA",
                            Weight = 1038
                        },
                        new
                        {
                            Id = new Guid("12d92793-279c-4fa4-a2a0-1f6e8732c7cf"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-MENDOZA",
                            Weight = 1029
                        },
                        new
                        {
                            Id = new Guid("50e386e9-1281-4abd-a744-5558be08c73b"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            SegmentIdentifierName = "LA_PLATA-NEUQUEN",
                            Weight = 1005
                        },
                        new
                        {
                            Id = new Guid("eb1b6dd8-6071-46ae-a568-bd33600cf674"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-CABA",
                            Weight = 986
                        },
                        new
                        {
                            Id = new Guid("2e49f448-3953-4135-b465-d63aa386c0cd"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-CORDOBA",
                            Weight = 340
                        },
                        new
                        {
                            Id = new Guid("bd5965e0-8258-48c9-941b-c3a516626f50"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-CORRIENTES",
                            Weight = 814
                        },
                        new
                        {
                            Id = new Guid("dc428e25-a3cc-4045-82a0-4b4ade6eff7d"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-FORMOSA",
                            Weight = 927
                        },
                        new
                        {
                            Id = new Guid("887feb03-4c76-40a9-aa3b-8be17181f866"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-LA_PLATA",
                            Weight = 1038
                        },
                        new
                        {
                            Id = new Guid("534c290a-ab4b-440f-a290-8f43b60024ed"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-MENDOZA",
                            Weight = 427
                        },
                        new
                        {
                            Id = new Guid("df8499dd-5086-412e-bedf-0616d9f574c7"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            SegmentIdentifierName = "LA_RIOJA-NEUQUEN",
                            Weight = 1063
                        },
                        new
                        {
                            Id = new Guid("df3b4652-69ed-4d41-b7bc-8492da732e29"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-CABA",
                            Weight = 985
                        },
                        new
                        {
                            Id = new Guid("74a96f8e-13c8-4ab2-a43b-19171c9fcd16"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-CORDOBA",
                            Weight = 466
                        },
                        new
                        {
                            Id = new Guid("15d4eebe-61fa-491e-9bac-32acc2717d78"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-CORRIENTES",
                            Weight = 1131
                        },
                        new
                        {
                            Id = new Guid("35254348-48e6-42ce-b2cd-c0d459cc933d"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-FORMOSA",
                            Weight = 1269
                        },
                        new
                        {
                            Id = new Guid("900bfff9-c6a0-4fd1-8828-82f69e013f58"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-LA_PLATA",
                            Weight = 1029
                        },
                        new
                        {
                            Id = new Guid("0f7b44ec-9e99-4049-a65e-98814abcb013"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-LA_RIOJA",
                            Weight = 427
                        },
                        new
                        {
                            Id = new Guid("87f11839-a5c7-4f1f-aedb-28b380e3b1bd"),
                            DestinationId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            OriginId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            SegmentIdentifierName = "MENDOZA-NEUQUEN",
                            Weight = 676
                        },
                        new
                        {
                            Id = new Guid("a435af28-aa89-4c96-805f-86578172f593"),
                            DestinationId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-CABA",
                            Weight = 989
                        },
                        new
                        {
                            Id = new Guid("ea552dde-3120-4ce2-a68c-2aeecf79060e"),
                            DestinationId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-CORDOBA",
                            Weight = 907
                        },
                        new
                        {
                            Id = new Guid("784a3b23-318a-45a1-8549-edbb51da4ff0"),
                            DestinationId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-CORRIENTES",
                            Weight = 1534
                        },
                        new
                        {
                            Id = new Guid("0b323af6-c51d-48c6-8442-826119ec5e39"),
                            DestinationId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-FORMOSA",
                            Weight = 1690
                        },
                        new
                        {
                            Id = new Guid("88b1c1a0-f3c5-476e-987f-d7692c9d8991"),
                            DestinationId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-LA_PLATA",
                            Weight = 1005
                        },
                        new
                        {
                            Id = new Guid("dd6c1c40-8e33-43bf-919d-820b7cc17d70"),
                            DestinationId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-LA_RIOJA",
                            Weight = 1063
                        },
                        new
                        {
                            Id = new Guid("46ad52fe-3447-4ada-a11b-b2f7e3bdb8a6"),
                            DestinationId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            OriginId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            SegmentIdentifierName = "NEUQUEN-MENDOZA",
                            Weight = 676
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Route");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Detail = "LA_RIOJA - CORDOBA - NEUQUEN - CABA - FORMOSA - LA_RIOJA",
                            Distance = 4096
                        },
                        new
                        {
                            Id = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Detail = "CORRIENTES - LA_PLATA - NEUQUEN - MENDOZA - LA_RIOJA - CORRIENTES",
                            Distance = 3752
                        },
                        new
                        {
                            Id = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            Detail = "FORMOSA - CORRIENTES - CABA - LA_PLATA - FORMOSA",
                            Distance = 1970
                        },
                        new
                        {
                            Id = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            Detail = "NEUQUEN - MENDOZA - LA_RIOJA - FORMOSA - CORDOBA - NEUQUEN",
                            Distance = 3761
                        },
                        new
                        {
                            Id = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            Detail = "LA_RIOJA - CORRIENTES - CABA - LA_PLATA - NEUQUEN - CORDOBA - LA_RIOJA",
                            Distance = 3911
                        },
                        new
                        {
                            Id = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Detail = "MENDOZA - LA_PLATA - FORMOSA - CORDOBA - MENDOZA",
                            Distance = 3287
                        },
                        new
                        {
                            Id = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Detail = "CORRIENTES - LA_PLATA - CABA - MENDOZA - CORDOBA - CORRIENTES",
                            Distance = 3011
                        });
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("RouteId", "NodeId", "Order");

                    b.HasIndex("NodeId");

                    b.ToTable("RouteNode");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            NodeId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            NodeId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            NodeId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            NodeId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            NodeId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("bffec97d-db7f-44eb-a511-1d8c7df44926"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            Order = 6
                        },
                        new
                        {
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            NodeId = new Guid("244cb214-f2f7-4349-b6f5-bb4aca5952fe"),
                            Order = 7
                        },
                        new
                        {
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            NodeId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            NodeId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            NodeId = new Guid("60379ffe-224c-4c26-9889-b3f79fc6c796"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            NodeId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            NodeId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 1
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("41c38ccb-bd46-4db1-97c8-387b67565d87"),
                            Order = 2
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("bab6add0-7481-4e1c-8014-b961f6e13a31"),
                            Order = 3
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("929c149e-bd42-4910-bcff-28cab658b4b6"),
                            Order = 4
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("424dbbe3-14c3-409c-9db2-0c2790a325e3"),
                            Order = 5
                        },
                        new
                        {
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            NodeId = new Guid("f9d1db7a-da61-45f5-bd9c-13e74c7d85f3"),
                            Order = 6
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CurrentSegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateScheduled")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransportationVehicleLicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSegmentId");

                    b.HasIndex("RouteId");

                    b.HasIndex("TransportationVehicleLicensePlate");

                    b.ToTable("Shipping");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d943f20b-d570-43be-9011-b1487f7a048e"),
                            DateScheduled = new DateTime(2020, 7, 17, 15, 48, 1, 321, DateTimeKind.Local).AddTicks(4630),
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("b88c413f-bb08-42f4-ac18-66ca9c32d872"),
                            DateCompleted = new DateTime(2020, 6, 29, 15, 48, 1, 382, DateTimeKind.Local).AddTicks(2430),
                            DateScheduled = new DateTime(2020, 6, 26, 15, 48, 1, 382, DateTimeKind.Local).AddTicks(2430),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("db6b85ea-a976-4b70-93d1-112cee2e27a1"),
                            DateCompleted = new DateTime(2020, 6, 25, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(180),
                            DateScheduled = new DateTime(2020, 6, 22, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(180),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("1eb8966d-ec38-4a14-9ff8-0b01c493316a"),
                            DateCompleted = new DateTime(2020, 6, 21, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(260),
                            DateScheduled = new DateTime(2020, 6, 18, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(260),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("55f80a09-3bad-4c2e-ae05-88b1c3858fd5"),
                            DateCompleted = new DateTime(2020, 6, 17, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(280),
                            DateScheduled = new DateTime(2020, 6, 14, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(280),
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("c3254969-5d1b-4254-9668-03393cdd7217"),
                            DateCompleted = new DateTime(2020, 6, 13, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(310),
                            DateScheduled = new DateTime(2020, 6, 10, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(310),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("4047753c-d566-4252-b904-deaa81cd4d57"),
                            DateCompleted = new DateTime(2020, 6, 9, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(320),
                            DateScheduled = new DateTime(2020, 6, 6, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(320),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("361077fc-eee3-4d0a-a4e5-163076462788"),
                            DateCompleted = new DateTime(2020, 6, 5, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(330),
                            DateScheduled = new DateTime(2020, 6, 2, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(330),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("fab7d620-b095-40e0-a740-7c4c95204567"),
                            DateCompleted = new DateTime(2020, 6, 1, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(340),
                            DateScheduled = new DateTime(2020, 5, 29, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(340),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("3108808e-a9e1-4fba-97b5-7386973d5e8f"),
                            CurrentSegmentId = new Guid("74a96f8e-13c8-4ab2-a43b-19171c9fcd16"),
                            DateScheduled = new DateTime(2020, 7, 3, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(360),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_1"
                        },
                        new
                        {
                            Id = new Guid("4fe4a738-a3bf-4718-8117-69fdd5f13d70"),
                            DateScheduled = new DateTime(2020, 7, 9, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2770),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("d5731384-72dd-4b50-a87d-dc6418215a4e"),
                            DateCompleted = new DateTime(2020, 5, 20, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2800),
                            DateScheduled = new DateTime(2020, 5, 17, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2800),
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("dfc47553-b8cf-47ea-892f-a264d0362e30"),
                            DateCompleted = new DateTime(2020, 5, 16, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2810),
                            DateScheduled = new DateTime(2020, 5, 13, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2810),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("20decf70-78bd-4ff6-a4aa-ad4178274dd0"),
                            DateCompleted = new DateTime(2020, 5, 12, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2820),
                            DateScheduled = new DateTime(2020, 5, 9, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2820),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("b1cf150b-f07b-459b-8326-414f516b86e6"),
                            DateCompleted = new DateTime(2020, 5, 8, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2840),
                            DateScheduled = new DateTime(2020, 5, 5, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2840),
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("a5ccfdfe-31f5-417e-9a01-03413250d581"),
                            DateCompleted = new DateTime(2020, 5, 4, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2840),
                            DateScheduled = new DateTime(2020, 5, 1, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2840),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("f9c3b9d4-fd30-4181-9c8a-8195d7022b13"),
                            DateCompleted = new DateTime(2020, 4, 30, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2850),
                            DateScheduled = new DateTime(2020, 4, 27, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(2850),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("45bb0310-f4ad-4906-95ec-aa77856472c2"),
                            DateCompleted = new DateTime(2020, 4, 26, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3000),
                            DateScheduled = new DateTime(2020, 4, 23, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3000),
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("36c5ccad-3507-40e4-b59b-d1e0ea9eee32"),
                            CurrentSegmentId = new Guid("bdace210-3d55-4b1e-8046-c0cefe46194c"),
                            DateScheduled = new DateTime(2020, 7, 3, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3010),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("e157b320-d4f4-4121-9a92-41ff0a8cf612"),
                            DateCompleted = new DateTime(2020, 4, 18, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3070),
                            DateScheduled = new DateTime(2020, 4, 15, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3070),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_2"
                        },
                        new
                        {
                            Id = new Guid("1f832d47-6697-4d36-b043-1e7351cfb098"),
                            DateScheduled = new DateTime(2020, 7, 5, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3080),
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            Status = 0,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("774e048a-8fab-4776-a200-9f590c38851b"),
                            DateCompleted = new DateTime(2020, 4, 10, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3090),
                            DateScheduled = new DateTime(2020, 4, 7, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3090),
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("925c7e0f-e29d-48c3-818f-a607edd83e99"),
                            DateCompleted = new DateTime(2020, 4, 6, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3100),
                            DateScheduled = new DateTime(2020, 4, 3, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3100),
                            RouteId = new Guid("d293135a-4900-4ae4-a93a-b4a60940c64d"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("4100d109-bfda-41f6-9459-45e9314de5c2"),
                            DateCompleted = new DateTime(2020, 4, 2, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3110),
                            DateScheduled = new DateTime(2020, 3, 30, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3110),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("341fe6db-80ba-4494-b823-3c6ab0834569"),
                            DateCompleted = new DateTime(2020, 3, 29, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3120),
                            DateScheduled = new DateTime(2020, 3, 26, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3120),
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("bc36d626-c0c1-44da-af03-9acc6ac04b16"),
                            DateCompleted = new DateTime(2020, 3, 25, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3130),
                            DateScheduled = new DateTime(2020, 3, 22, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3130),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("6071c01c-1d4b-400d-8d84-d6421094a0d9"),
                            DateCompleted = new DateTime(2020, 3, 21, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3140),
                            DateScheduled = new DateTime(2020, 3, 18, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3140),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("29f207f4-afba-4596-922f-fc3fe9d47e11"),
                            CurrentSegmentId = new Guid("a64a46fb-d9cf-40b4-87b9-23d795b174df"),
                            DateScheduled = new DateTime(2020, 7, 1, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3150),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 2,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("d9706d8a-2804-4833-9a81-41738595499a"),
                            DateCompleted = new DateTime(2020, 3, 13, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3160),
                            DateScheduled = new DateTime(2020, 3, 10, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3160),
                            RouteId = new Guid("90e47a89-b112-4dd8-b936-e157e05f8e4e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("12113eda-b968-4e1f-91b1-112b43c3bf68"),
                            DateCompleted = new DateTime(2020, 3, 9, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3160),
                            DateScheduled = new DateTime(2020, 3, 6, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3160),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_3"
                        },
                        new
                        {
                            Id = new Guid("b094fec4-4ce1-4abd-b42f-2025cbd4e47a"),
                            DateCompleted = new DateTime(2020, 3, 5, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3170),
                            DateScheduled = new DateTime(2020, 3, 2, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3170),
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("2bd55405-9455-4d3b-be50-edcaf28211e5"),
                            DateCompleted = new DateTime(2020, 3, 1, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3180),
                            DateScheduled = new DateTime(2020, 2, 27, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3180),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("5b0e3c10-e300-48cc-b264-850484b5524c"),
                            DateCompleted = new DateTime(2020, 2, 26, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3190),
                            DateScheduled = new DateTime(2020, 2, 23, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3190),
                            RouteId = new Guid("36fb10cb-a571-4104-a40b-07c2f1e39868"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("54b5567d-88be-4d5d-951c-d4af1d2b2aa7"),
                            DateCompleted = new DateTime(2020, 2, 22, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3210),
                            DateScheduled = new DateTime(2020, 2, 19, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3210),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("854a08e6-a396-4329-bd67-bf99f0232083"),
                            DateCompleted = new DateTime(2020, 2, 18, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3220),
                            DateScheduled = new DateTime(2020, 2, 15, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3220),
                            RouteId = new Guid("6d96972b-60c1-4428-96f3-6647b281124e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("b976bc40-6df7-4a14-b986-39532d622ce8"),
                            DateCompleted = new DateTime(2020, 2, 14, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3220),
                            DateScheduled = new DateTime(2020, 2, 11, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3220),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("485e91c5-e297-4d83-b521-c0224cb46273"),
                            DateCompleted = new DateTime(2020, 2, 10, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3230),
                            DateScheduled = new DateTime(2020, 2, 7, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3230),
                            RouteId = new Guid("195dfd27-b531-4b58-a20c-faaab3fa8c80"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("95d7bde5-be93-4e45-b695-3c828aa9f303"),
                            DateCompleted = new DateTime(2020, 2, 6, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3240),
                            DateScheduled = new DateTime(2020, 2, 3, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3240),
                            RouteId = new Guid("80c1e20f-0ec2-4f98-8c40-c881b614824e"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("0ba0e67d-5d65-4610-b69c-f415ba3071f2"),
                            DateCompleted = new DateTime(2020, 2, 2, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3250),
                            DateScheduled = new DateTime(2020, 1, 30, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3250),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        },
                        new
                        {
                            Id = new Guid("53ab01e1-60f4-4648-abd4-d2e56c0c634d"),
                            DateCompleted = new DateTime(2020, 1, 29, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3260),
                            DateScheduled = new DateTime(2020, 1, 26, 15, 48, 1, 384, DateTimeKind.Local).AddTicks(3260),
                            RouteId = new Guid("19af0191-53eb-4250-a4db-a6ef8679840b"),
                            Status = 1,
                            TransportationVehicleLicensePlate = "SCANIA_4"
                        });
                });

            modelBuilder.Entity("LogisticsDomain.TransportationVehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("LicensePlate");

                    b.ToTable("TransportationVehicle");

                    b.HasData(
                        new
                        {
                            LicensePlate = "SCANIA_1",
                            Model = "Scania G 410",
                            Year = 2000
                        },
                        new
                        {
                            LicensePlate = "SCANIA_2",
                            Model = "Scania P 320",
                            Year = 2010
                        },
                        new
                        {
                            LicensePlate = "SCANIA_3",
                            Model = "Scania R 450",
                            Year = 2015
                        },
                        new
                        {
                            LicensePlate = "SCANIA_4",
                            Model = "Scania R 620",
                            Year = 2017
                        });
                });

            modelBuilder.Entity("LogisticsDomain.Path", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Destination")
                        .WithMany("PathAsDestination")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Node", "Origin")
                        .WithMany("PathAsOrigin")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.RouteNode", b =>
                {
                    b.HasOne("LogisticsDomain.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("RouteNodes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("LogisticsDomain.Shipping", b =>
                {
                    b.HasOne("LogisticsDomain.Path", "CurrentSegment")
                        .WithMany()
                        .HasForeignKey("CurrentSegmentId");

                    b.HasOne("LogisticsDomain.Route", "Route")
                        .WithMany("Shippings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogisticsDomain.TransportationVehicle", "TransportationVehicle")
                        .WithMany("Shippings")
                        .HasForeignKey("TransportationVehicleLicensePlate")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
