// <auto-generated />
using System;
using LogisticsCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LogisticsCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logistics.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Node");

                    b.HasData(
                        new
                        {
                            Id = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Name = "CABA"
                        },
                        new
                        {
                            Id = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Name = "Córdoba"
                        },
                        new
                        {
                            Id = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Name = "Corrientes"
                        },
                        new
                        {
                            Id = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Name = "Formosa"
                        },
                        new
                        {
                            Id = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Name = "La Plata"
                        },
                        new
                        {
                            Id = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Name = "La Rioja"
                        },
                        new
                        {
                            Id = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Name = "Mendoza"
                        },
                        new
                        {
                            Id = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Name = "Neuquén"
                        });
                });

            modelBuilder.Entity("Logistics.Models.Path", b =>
                {
                    b.Property<Guid>("OriginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("OriginId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Path");

                    b.HasData(
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 646
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 792
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 933
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 53
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 986
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 985
                        },
                        new
                        {
                            OriginId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 989
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 646
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 677
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 824
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 698
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 340
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 466
                        },
                        new
                        {
                            OriginId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 907
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 792
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 677
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 157
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 830
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 814
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 1131
                        },
                        new
                        {
                            OriginId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 1534
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 933
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 824
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 157
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 968
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 927
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 1269
                        },
                        new
                        {
                            OriginId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 1690
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 53
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 698
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 830
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 968
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 1038
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 1029
                        },
                        new
                        {
                            OriginId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 1005
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 986
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 340
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 814
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 927
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 1038
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 427
                        },
                        new
                        {
                            OriginId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 1063
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 985
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 466
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 1131
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 1269
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 1029
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 427
                        },
                        new
                        {
                            OriginId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            DestinationId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            Weight = 676
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("98f457c9-aa02-4d6b-8013-ecb3f4fb1785"),
                            Weight = 989
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("2272753e-7939-4c53-92b8-40182d578338"),
                            Weight = 907
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("e5af2896-4670-4d7d-aa06-d78ca1fbbf54"),
                            Weight = 1534
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("10de5c0a-0fb9-462d-83ba-6b5ac7c48095"),
                            Weight = 1690
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("ca6bd0cf-a01d-4d3a-aeb9-1dac90901bc7"),
                            Weight = 1005
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("7eb35662-4380-4a6a-a978-446b342cd39f"),
                            Weight = 1063
                        },
                        new
                        {
                            OriginId = new Guid("9adc8373-3399-406d-ac49-e894229e6d05"),
                            DestinationId = new Guid("f0b8952a-9613-4ae8-936d-c4a6742a47a6"),
                            Weight = 676
                        });
                });

            modelBuilder.Entity("Logistics.Models.Path", b =>
                {
                    b.HasOne("Logistics.Models.Node", "Destination")
                        .WithMany("PathAsDestination")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Logistics.Models.Node", "Origin")
                        .WithMany("PathAsOrigin")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
